### ISSUE TITLE
Suggestion: Use data from Spotify app instead of requiring credentials

### ISSUE THREAD

**Issue by nanna7077** [newpolygons/Blueberry#1]
It would be nice if the program could get the content from the Spotify app instead of requiring the credentials which would kind of put off some users.
By the way, nice work!

**Comment by newpolygons** [comment]
You make a good point having to authenticate is annoying, unfortunately it is required in order to get the users active song.

**Comment by nanna7077** [comment]
I dont think so. At least when you have the app installed. I made something similar yesterday which does not need authentication https://github.com/nanna7077/WallSpot
I have linked to this project as my inspiration :D

**Comment by newpolygons** [comment]
Oh really thanks for the heads up :) I'll look into it today.

**Comment by nanna7077** [comment]
good luck!

**Comment by newpolygons** [comment]
This issue has been resolved in the latest commit.

Thank you
