### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by Dukko** [newpolygons/Blueberry#2]
Trying to install this on Manjaro. 

> pip3 install appscript                                                                                                          ✔ 
> Defaulting to user installation because normal site-packages is not writeable
> Collecting appscript
>   Using cached appscript-1.2.2.tar.gz (293 kB)
>   Preparing metadata (setup.py) ... done
> Requirement already satisfied: lxml>=4.7.1 in ./.local/lib/python3.10/site-packages (from appscript) (4.9.2)
> Building wheels for collected packages: appscript
>   Building wheel for appscript (setup.py) ... error
>   error: subprocess-exited-with-error
>   
>   × python setup.py bdist_wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [39 lines of output]
>       running bdist_wheel
>       running build
>       running build_py
>       creating build
>       creating build/lib.linux-x86_64-cpython-310
>       copying lib/mactypes.py -> build/lib.linux-x86_64-cpython-310
>       copying lib/osax.py -> build/lib.linux-x86_64-cpython-310
>       creating build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/typewrappers.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/mactypes.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/kae.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/findapp.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/aemsend.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/aemreference.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/aemconnect.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/aemcodecs.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/__init__.py -> build/lib.linux-x86_64-cpython-310/aem
>       creating build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/terminology.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/sdefparser.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/reservedkeywords.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/referencerenderer.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/reference.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/keywordwrapper.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/genericreference.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/defaultterminology.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/aeteparser.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/__init__.py -> build/lib.linux-x86_64-cpython-310/appscript
>       running build_ext
>       building 'aem.ae' extension
>       creating build/temp.linux-x86_64-cpython-310
>       creating build/temp.linux-x86_64-cpython-310/ext
>       gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -ffat-lto-objects -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -fPIC -I/usr/include/python3.10 -c ext/ae.c -o build/temp.linux-x86_64-cpython-310/ext/ae.o -DMAC_OS_X_VERSION_MIN_REQUIRED=MAC_OS_X_VERSION_10_12 -D__LP64__
>       In file included from ext/ae.c:16:
>       ext/ae.h:26:10: fatal error: Carbon/Carbon.h: No such file or directory
>          26 | #include <Carbon/Carbon.h>
>             |          ^~~~~~~~~~~~~~~~~
>       compilation terminated.
>       error: command '/usr/bin/gcc' failed with exit code 1
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for appscript
>   Running setup.py clean for appscript
> Failed to build appscript
> Installing collected packages: appscript
>   Running setup.py install for appscript ... error
>   error: subprocess-exited-with-error
>   
>   × Running setup.py install for appscript did not run successfully.
>   │ exit code: 1
>   ╰─> [42 lines of output]
>       running install
>       /usr/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
>         warnings.warn(
>       Distribution option extra_path is deprecated. See issue27919 for details.
>       running build
>       running build_py
>       creating build
>       creating build/lib.linux-x86_64-cpython-310
>       copying lib/mactypes.py -> build/lib.linux-x86_64-cpython-310
>       copying lib/osax.py -> build/lib.linux-x86_64-cpython-310
>       creating build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/typewrappers.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/mactypes.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/kae.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/findapp.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/aemsend.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/aemreference.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/aemconnect.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/aemcodecs.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/__init__.py -> build/lib.linux-x86_64-cpython-310/aem
>       creating build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/terminology.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/sdefparser.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/reservedkeywords.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/referencerenderer.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/reference.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/keywordwrapper.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/genericreference.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/defaultterminology.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/aeteparser.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/__init__.py -> build/lib.linux-x86_64-cpython-310/appscript
>       running build_ext
>       building 'aem.ae' extension
>       creating build/temp.linux-x86_64-cpython-310
>       creating build/temp.linux-x86_64-cpython-310/ext
>       gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -ffat-lto-objects -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -fPIC -I/usr/include/python3.10 -c ext/ae.c -o build/temp.linux-x86_64-cpython-310/ext/ae.o -DMAC_OS_X_VERSION_MIN_REQUIRED=MAC_OS_X_VERSION_10_12 -D__LP64__
>       In file included from ext/ae.c:16:
>       ext/ae.h:26:10: fatal error: Carbon/Carbon.h: No such file or directory
>          26 | #include <Carbon/Carbon.h>
>             |          ^~~~~~~~~~~~~~~~~
>       compilation terminated.
>       error: command '/usr/bin/gcc' failed with exit code 1
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: legacy-install-failure
> 
> × Encountered error while trying to install package.
> ╰─> appscript
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for output from the failure.
>     ~  pip install Cmake                                                                                                             1 ✘ 
> Defaulting to user installation because normal site-packages is not writeable
> Collecting Cmake
>   Downloading cmake-3.26.3-py2.py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (24.0 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.0/24.0 MB 27.0 MB/s eta 0:00:00
> Installing collected packages: Cmake
> Successfully installed Cmake-3.26.3
>     ~  pip3 install appscript                                                                                                          ✔ 
> Defaulting to user installation because normal site-packages is not writeable
> Collecting appscript
>   Using cached appscript-1.2.2.tar.gz (293 kB)
>   Preparing metadata (setup.py) ... done
> Requirement already satisfied: lxml>=4.7.1 in ./.local/lib/python3.10/site-packages (from appscript) (4.9.2)
> Building wheels for collected packages: appscript
>   Building wheel for appscript (setup.py) ... error
>   error: subprocess-exited-with-error
>   
>   × python setup.py bdist_wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [39 lines of output]
>       running bdist_wheel
>       running build
>       running build_py
>       creating build
>       creating build/lib.linux-x86_64-cpython-310
>       copying lib/mactypes.py -> build/lib.linux-x86_64-cpython-310
>       copying lib/osax.py -> build/lib.linux-x86_64-cpython-310
>       creating build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/typewrappers.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/mactypes.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/kae.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/findapp.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/aemsend.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/aemreference.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/aemconnect.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/aemcodecs.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/__init__.py -> build/lib.linux-x86_64-cpython-310/aem
>       creating build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/terminology.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/sdefparser.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/reservedkeywords.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/referencerenderer.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/reference.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/keywordwrapper.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/genericreference.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/defaultterminology.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/aeteparser.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/__init__.py -> build/lib.linux-x86_64-cpython-310/appscript
>       running build_ext
>       building 'aem.ae' extension
>       creating build/temp.linux-x86_64-cpython-310
>       creating build/temp.linux-x86_64-cpython-310/ext
>       gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -ffat-lto-objects -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -fPIC -I/usr/include/python3.10 -c ext/ae.c -o build/temp.linux-x86_64-cpython-310/ext/ae.o -DMAC_OS_X_VERSION_MIN_REQUIRED=MAC_OS_X_VERSION_10_12 -D__LP64__
>       In file included from ext/ae.c:16:
>       ext/ae.h:26:10: fatal error: Carbon/Carbon.h: No such file or directory
>          26 | #include <Carbon/Carbon.h>
>             |          ^~~~~~~~~~~~~~~~~
>       compilation terminated.
>       error: command '/usr/bin/gcc' failed with exit code 1
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for appscript
>   Running setup.py clean for appscript
> Failed to build appscript
> Installing collected packages: appscript
>   Running setup.py install for appscript ... error
>   error: subprocess-exited-with-error
>   
>   × Running setup.py install for appscript did not run successfully.
>   │ exit code: 1
>   ╰─> [42 lines of output]
>       running install
>       /usr/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
>         warnings.warn(
>       Distribution option extra_path is deprecated. See issue27919 for details.
>       running build
>       running build_py
>       creating build
>       creating build/lib.linux-x86_64-cpython-310
>       copying lib/mactypes.py -> build/lib.linux-x86_64-cpython-310
>       copying lib/osax.py -> build/lib.linux-x86_64-cpython-310
>       creating build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/typewrappers.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/mactypes.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/kae.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/findapp.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/aemsend.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/aemreference.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/aemconnect.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/aemcodecs.py -> build/lib.linux-x86_64-cpython-310/aem
>       copying lib/aem/__init__.py -> build/lib.linux-x86_64-cpython-310/aem
>       creating build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/terminology.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/sdefparser.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/reservedkeywords.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/referencerenderer.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/reference.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/keywordwrapper.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/genericreference.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/defaultterminology.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/aeteparser.py -> build/lib.linux-x86_64-cpython-310/appscript
>       copying lib/appscript/__init__.py -> build/lib.linux-x86_64-cpython-310/appscript
>       running build_ext
>       building 'aem.ae' extension
>       creating build/temp.linux-x86_64-cpython-310
>       creating build/temp.linux-x86_64-cpython-310/ext
>       gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -ffat-lto-objects -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -fPIC -I/usr/include/python3.10 -c ext/ae.c -o build/temp.linux-x86_64-cpython-310/ext/ae.o -DMAC_OS_X_VERSION_MIN_REQUIRED=MAC_OS_X_VERSION_10_12 -D__LP64__
>       In file included from ext/ae.c:16:
>       ext/ae.h:26:10: fatal error: Carbon/Carbon.h: No such file or directory
>          26 | #include <Carbon/Carbon.h>
>             |          ^~~~~~~~~~~~~~~~~
>       compilation terminated.
>       error: command '/usr/bin/gcc' failed with exit code 1
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: legacy-install-failure
> 
> × Encountered error while trying to install package.
> ╰─> appscript
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for output from the failure.

**Comment by newpolygons** [comment]
Hey looks like appscript is failing to install. This is used for MacOS compatibility. Since you are trying to use the application on Linux I recommend removing appscript from the requirements.txt  file. Hope this helps!
